### ISSUE TITLE
A tale of two flag_chans.py

### ISSUE THREAD

**Issue by yupinghuang** [ovro-lwa/distributed-pipeline#13]
https://github.com/ovro-lwa/distributed-pipeline/blob/master/orca/flagging/flag_bad_chans.py I think is the original flag_bad_chans.20180206.py and then I updated it to include the --apply-flag flag.

https://github.com/ovro-lwa/distributed-pipeline/blob/master/orca/flagging/flag_bad_chans.20180206.py seems to be an updated version that also works on cross-hand vis.

Also all of these codes are supposed to work fine on visiblity that already has some of their channels flagged. @marinanderson to verify.

Also suggestions from @marinanderson : 
I was planning on either renaming the flag_bad_chans.20180206.py that I added or adding it into flag_bad_chans.py as a separate function called…like…flag_bad_chans_crosshands or something. Or maybe merge it into the existing function with an option docrosshands: bool = False?

**Comment by marinanderson** [comment]
Deleted the duplicate flag_bad_chans.20180206.py and merged cross-hand vis (with crosshand=False option) into pre-existing flag_bad_chans.py.
